project:
  type: website

website:
  title: "NeutrinoHit"
  site-url: "https://neutrinohit.github.io/"
  repo-url: "https://github.com/NeutrinoHit/NeutrinoHit.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Главная
      - href: books.qmd
        text: Книги
      - href: lectures.qmd
        text: Лекции
      - href: scipop.qmd
        text: Научпоп
      - href: animations.qmd
        text: Анимации
      - href: software.qmd
        text: Код
  page-footer:
    left: "© NeutrinoHit"
    right: "Built with Quarto"

format:
  html:
    theme: cosmo
    toc: true
    lang: ru
    css: styles.css
