#!/usr/bin/env python3
"""Publish a NeutrinoHit photo album to a Telegram channel.

The script reads album.json generated by Photo Studio. By default it performs a
dry run; pass --send to call the Telegram Bot API.
"""

from __future__ import annotations

import argparse
import json
import mimetypes
import os
import sys
import time
import uuid
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


TELEGRAM_BATCH_SIZE = 10
TELEGRAM_CAPTION_LIMIT = 1024


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Publish a NeutrinoHit album.json to Telegram."
    )
    parser.add_argument("album", type=Path, help="Path to album.json")
    parser.add_argument(
        "--chat",
        default=os.environ.get("TELEGRAM_CHAT_ID"),
        help="Telegram channel/chat id, e.g. @neutrinohit",
    )
    parser.add_argument(
        "--token-env",
        default="TELEGRAM_BOT_TOKEN",
        help="Environment variable containing the bot token",
    )
    parser.add_argument(
        "--send",
        action="store_true",
        help="Actually publish. Without this flag the script prints a dry run.",
    )
    parser.add_argument(
        "--site-url",
        default=None,
        help="Override album URL placed into Telegram captions.",
    )
    parser.add_argument(
        "--sleep",
        type=float,
        default=1.0,
        help="Delay between Telegram requests in seconds.",
    )
    parser.add_argument(
        "--silent",
        action="store_true",
        help="Send without notification.",
    )
    parser.add_argument(
        "--protect-content",
        action="store_true",
        help="Prevent forwarding/saving in Telegram clients that support it.",
    )
    return parser.parse_args()


def load_album(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        data = json.load(handle)
    if not isinstance(data, dict):
        raise ValueError("album.json must contain an object")
    if not data.get("photos"):
        raise ValueError("album.json contains no photos")
    return data


def chunked(items: list[Any], size: int) -> list[list[Any]]:
    return [items[index : index + size] for index in range(0, len(items), size)]


def clean_caption(caption: str) -> str:
    caption = "\n".join(line.rstrip() for line in caption.splitlines()).strip()
    if len(caption) <= TELEGRAM_CAPTION_LIMIT:
        return caption
    return caption[: TELEGRAM_CAPTION_LIMIT - 1].rstrip() + "…"


def album_caption(
    album: dict[str, Any],
    batch_index: int,
    total_batches: int,
    site_url: str | None,
) -> str:
    lines: list[str] = []
    title = str(album.get("title") or "Фотоальбом").strip()
    date = str(album.get("date") or "").strip()
    place = str(album.get("place") or "").strip()
    post_text = str(album.get("postText") or album.get("telegramText") or "").strip()
    summary = str(album.get("summary") or "").strip()
    url = site_url or str(album.get("siteUrl") or "").strip()

    if title:
        lines.append(title)
    if date or place:
        lines.append(" · ".join(part for part in (date, place) if part))
    if batch_index == 0:
        body = post_text or summary
        if body:
            lines.append(body)
    if total_batches > 1:
        lines.append(f"Часть {batch_index + 1}/{total_batches}")
    if url:
        lines.append(url)
    return clean_caption("\n\n".join(lines))


def photo_path(album_path: Path, photo: dict[str, Any]) -> Path:
    rel = photo.get("file")
    if not rel:
        raise ValueError("Photo item without file")
    path = Path(str(rel))
    if not path.is_absolute():
        path = album_path.parent / path
    return path


def encode_multipart(
    fields: dict[str, str],
    files: dict[str, Path],
) -> tuple[bytes, str]:
    boundary = "----neutrinohit-" + uuid.uuid4().hex
    chunks: list[bytes] = []

    for name, value in fields.items():
        chunks.append(f"--{boundary}\r\n".encode("utf-8"))
        chunks.append(
            f'Content-Disposition: form-data; name="{name}"\r\n\r\n'.encode("utf-8")
        )
        chunks.append(str(value).encode("utf-8"))
        chunks.append(b"\r\n")

    for name, path in files.items():
        filename = path.name
        content_type = mimetypes.guess_type(filename)[0] or "application/octet-stream"
        chunks.append(f"--{boundary}\r\n".encode("utf-8"))
        chunks.append(
            (
                f'Content-Disposition: form-data; name="{name}"; '
                f'filename="{filename}"\r\n'
            ).encode("utf-8")
        )
        chunks.append(f"Content-Type: {content_type}\r\n\r\n".encode("utf-8"))
        chunks.append(path.read_bytes())
        chunks.append(b"\r\n")

    chunks.append(f"--{boundary}--\r\n".encode("utf-8"))
    return b"".join(chunks), "multipart/form-data; boundary=" + boundary


def telegram_request(
    token: str,
    method: str,
    fields: dict[str, str],
    files: dict[str, Path],
) -> dict[str, Any]:
    body, content_type = encode_multipart(fields, files)
    request = urllib.request.Request(
        url=f"https://api.telegram.org/bot{token}/{method}",
        data=body,
        headers={"Content-Type": content_type},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=120) as response:
            payload = response.read().decode("utf-8")
    except urllib.error.HTTPError as error:
        details = error.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Telegram HTTP {error.code}: {details}") from error
    result = json.loads(payload)
    if not result.get("ok"):
        raise RuntimeError(f"Telegram error: {payload}")
    return result


def publish_album(args: argparse.Namespace) -> int:
    album_path = args.album.resolve()
    album = load_album(album_path)
    photos = album["photos"]
    batches = chunked(photos, TELEGRAM_BATCH_SIZE)
    total_batches = len(batches)

    for photo in photos:
        path = photo_path(album_path, photo)
        if not path.exists():
            raise FileNotFoundError(path)

    if args.send:
        if not args.chat:
            raise ValueError("--chat or TELEGRAM_CHAT_ID is required with --send")
        token = os.environ.get(args.token_env)
        if not token:
            raise ValueError(f"{args.token_env} is not set")
    else:
        token = ""

    for batch_index, batch in enumerate(batches):
        caption = album_caption(album, batch_index, total_batches, args.site_url)
        paths = [photo_path(album_path, photo) for photo in batch]
        method = "sendPhoto" if len(batch) == 1 else "sendMediaGroup"
        print(
            f"[{batch_index + 1}/{total_batches}] {method}: "
            f"{len(batch)} photo(s), caption {len(caption)}/{TELEGRAM_CAPTION_LIMIT}"
        )
        print(caption)
        print()

        if not args.send:
            continue

        common_fields = {
            "chat_id": args.chat,
            "disable_notification": "true" if args.silent else "false",
            "protect_content": "true" if args.protect_content else "false",
        }
        if len(batch) == 1:
            fields = {**common_fields, "caption": caption}
            telegram_request(token, "sendPhoto", fields, {"photo": paths[0]})
        else:
            media = []
            files: dict[str, Path] = {}
            for index, path in enumerate(paths):
                attach_name = f"photo{index}"
                item: dict[str, str] = {
                    "type": "photo",
                    "media": f"attach://{attach_name}",
                }
                if index == 0 and caption:
                    item["caption"] = caption
                media.append(item)
                files[attach_name] = path
            fields = {**common_fields, "media": json.dumps(media, ensure_ascii=False)}
            telegram_request(token, "sendMediaGroup", fields, files)

        if batch_index + 1 < total_batches:
            time.sleep(args.sleep)

    return 0


def main() -> int:
    args = parse_args()
    try:
        return publish_album(args)
    except Exception as error:
        print(f"error: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
